name="fireball"
value=300
tagline="smack down a massive ass fireball"
flavour="it's hot hot spicy spicy"

accuracy="1d20"
against_attribute="Dex"
label="Cast"
report="cast a fireball"
range=12

[area]
shape="Sphere"
size=3

[[effect]]
label="Cast"
type="AddStatus"
status="Burn"
duration = "Minute"

[[effect]]
type="Damage"
damage="3d10 + 5"
damage_type = ["Ignis", "Body" ]
