name = "Fine Sword"
level = 10
value = 1000

tagline = "A sword fit for a nobleman"
flavour = [
	"excelent craftsmanship and materials have created a fantastic weapon",
	"the blade is well balanced",
	"the grip is made from soft yet strong leather"
]

[equip]
label = "Wield"
slot = "OnHand"

[[action]]
type = "Attack"
label = "Attack"
damage = "2d10 + 7"
accuracy = "1d20 + 5"
damage_type = [ "Slicing", "Body" ]
range = 0
report = "attack the %{target} for %{damage} damage"

[[action]]
type = "Buff"
lasts_for = 1
time_to_complete = 0
label = "Block"
must_target = "Myself"
report = "shift into a defenceve stance"
buff = { attribute = "ArmorClass", polarity = "+", value = "1d6 + 3" } 
