name = "Fine Sword"
level = 10
value = 1000

tagline = "A sword fit for a nobleman"
flavour = [
	"excelent craftsmanship and materials have created a fantastic weapon",
	"the blade is well balanced",
	"the grip is made from soft yet strong leather"
]

[equip]
label = "Wield"
slot = "OnHand"

[[action]]
label = "Attack"
range = 0
report = "attack the %{target} for %{damage} damage"
	[[action.effect]]
	type = "Damage"
	damage = "2d10 + 7"
	accuracy = "1d20 + 5"
	damage_type = [ "Slicing", "Body" ]

[[action]]
label = "Block"
report = "shift into a defenceve stance"
range = 0
	[[action.effect]]
	type = "Buff"
	duration="Turn"
	buff = { attribute = "ArmorClass", polarity = "+", value = "1d6 + 3" } 
