name = "Plain Shortsword"

rarity = 500

description = [
	"A simple steel shortsword",
	"A shortsword with a comfortable leather-wrapped grip"
]

[equip]
label = "Wield"
slot = "OnHand"

[action]
type = "Attack"
label = "Attack"
damage = ["D12"]
accuracy = ["D20"]
damage_type = [ "Slicing", "Body" ]
report = "attack the %{target} for %{damage} damage"
