name="bless"
value=300
tagline="fill the target with effective goodness"
flavour="make them feel great"
mana=10

label="Cast"

[[effect]]
type="Buff"
duration="Minute"
attribute="Str"
value="1d4"

[[effect]]
type="Buff"
duration="Minute"
attribute="Con"
value="1d4"

[[effect]]
type="Buff"
duration="Minute"
attribute="Dex"
value="1d4"

[[effect]]
type="Buff"
duration="Minute"
attribute="Wis"
value="1d4"

[[effect]]
type="Buff"
duration="Minute"
attribute="Int"
value="1d4"

[[effect]]
type="Buff"
duration="Minute"
attribute="Cha"
value="1d4"
