name = "Green & Gold Ring"
identified_name = "Ring of Oxen Strength"
level = 12
value = 3000

tagline = "As strong (and stupid) as an Ox"

flavour = [
	"A thick golden ring with carvings of plows and horns",
	"Enamled horns hold a sparkling saphire",
	"The ring glows with a dancing internal light"
]

[equip]
label = "Wear"
slot = "Ring"

[[passive]]
attribute = "Str"
polarity = "+"
value = 2

[[passive]]
attribute = "Con"
polarity = "+"
value = 1

[[passive]]
attribute = "Int"
polarity = "-"
value = 2
