name = "Leather Boots"
value = 50
weight = 4

tagline = "Scuffed and well worn"
flavour = "the laces are a little torn"

[equip]
label = "Lace Up"
slot = "Feet"

[[passive]]
attribute = "ArmorClass"
value = "1"

[[passive]]
attribute = "LandSpeed"
value = "1"
