name = "Heal"
value = 100
tagline = "restore a portion of health"
flavour = "fill someone up with the red juice"
level=1
label="Cast"
range=15
report="heal %{target} for %{value} HP"

[[effect]]
type="Heal"
value="2d4 + 2"
