name = "Greater Health Potion"
level = 8
value = 1000

tagline = "This potion restores a portion of your health"
flavour = [
	"A common potion for restoring vitality",
	"The potion smells medicinally and herby",
	"The red liquid bubbles and seeths",
]

[consume]
label = "Take Potion"
report = "use a health potion on %{target}, for %{value} health!"
range = 1
	[[consume.effect]]
	type = "Heal"
	value = "8d8 + 8"
