name = "Standard Health Potion"
level = 3
value = 400

tagline = "This potion restores a portion of your health"
flavour = [
	"A common potion for restoring vitality",
	"The potion smells medicinally and herby",
	"The red liquid bubbles and seeths",
]

[[consume]]
type="Buff"
label = "Take Potion"
attribute = "Health"
value = "4d8 + 4"
consumes = true
report = "use a health potion on %{target}, for %{value} health!"
