name="Apple"
value=5

tagline="Round, shiny, and red"
flavour = [ "The french call this fruit \"le pomme de pommes\"" ]

[consume]
label = "Eat"
range = 0
report = "eat the apple"
time = "Minute"
	[[consume.effect]]
	type = "Heal"
	value = "5"
