name="grape"
value=1

tagline="A single grape"
flavour = [ "it's round and grapey" ]

[consume]
label = "Eat"
range = 0
report = "eat the grape"
time = "Turn"
	[[consume.effect]]
	type = "Heal"
	value = "1"
