name = "Loaf of Bread"
value = 20

tagline = "A tasty looking loaf of seeded bread"
flavour = []

[consume]
label = "Eat"
report = "eat that tastey bread"
time = "Minute"
	[[consume.effect]]
	type = "Heal"
	value = "20"
