name="Pot of Yoghurt"
value=15

tagline="There's a picture of a smiling pineapple on the side"
flavour = [ "Quite why anyone would carry this around on an adventure is beyond you" ]

[consume]
label = "Eat"
report = "spoon up the yog"
time = "Minute"
	[[consume.effect]]
	type = "Heal"
	value = "1d10 + 10"
