name = "Plain Fauchard"
level = 1
value = 50

tagline = "A long handled weapon with a one sided blade mounted at the end"
flavour = [
	"A dangerous martial weapon that originated in a far away land",
	"Harder to use than a sword, but just as dangerous with practice",
]

[equip]
label = "Wield"
slot = "TwoHand"

[[action]]
type = "Attack"
label = "Attack"
damage = "2d8 + 3"
accuracy = "1d20 + 5"
damage_type = [ "Slicing", "Body" ]
range = 1
report = "attack the %{target} for %{damage} damage"

[[action]]
type = "Buff"
label = "Block"
attribute = "ArmorClass"
duration = 1
must_target = "WithinRange"
report = "block incoming atacks against %{target}"
value = "1d4 + 2"
