name = "Simple Dagger"
level = 1
value = 20

tagline = "A simple, well balanced steel dagger"
flavour = [
	"A small blade, easy to weild and easy to hide",
	"A dagger, favourite weapon of sneaky bastards the world over",
]

[equip]
label = "Wield"
slot = "EitherHand"

[[action]]
label = "Attack"
report = "stab the %{target} for %{damage} damage"
accuracy = "1d20 + 5"
	[[action.effect]]
	type = "Damage"
	damage = "1d6 + 4"
	damage_type = [ "Poking", "Body" ]
