name = "Simple Greathammer"
level = 1
value = 50

tagline = "A large blunt melee weapon"
flavour = [
	"A weighty steel greathammer",
	"A dangerous and threatening looking hammer",
	"A simple and improvised weapon, for simple improvisers",
]

[equip]
label = "Heft"
slot = "TwoHand"

[[action]]
type = "Attack"
label = "Attack"
damage = "3d6 + 4"
accuracy = "1d20 + 5"
damage_type = [ "Bashing", "Body" ]
range = 1
report = "stab the %{target} for %{damage} damage"
