name = "Plain Shield"
level = 1
value = 20

tagline = "A simple wood and steel buckler"
flavour = [
	"A circular shield that offers moderate protection",
	"A serviceable shield, just ignore the dents",
]

[equip]
label = "Wield"
slot = "OffHand"

[[passive]]
attribute = "ArmorClass"
polarity = "+"
value = "2"

[[action]]
label = "Defend"
report = "raise my shield"
range = 1
	[[action.effect]]
	type = "Buff"
	buff = { attribute = "ArmorClass", polarity = "+", value = "1d4 + 2" }
	duration = "Turn"
