name = "Plain Shortsword"
level = 1
value = 50

tagline = "A simple steel shortsword"
flavour = [
	"A shortsword with a comfortable leather-wrapped grip",
	"The standard weapon of choice for new adventureres"
]

[equip]
label = "Wield"
slot = "OnHand"

[[action]]
label = "Attack"
range = 0
report = "attack the %{target} for %{damage} damage"
accuracy = "1d20 + 5"
	[[action.effect]]
	type = "Damage"
	damage = "1d12 + 5"
	damage_type = [ "Slicing", "Body" ]

[[action]]
label = "Block"
must_target = "Myself"
report = "shift into a defenceve stance"
range = 0
	[[action.effect]]
	type = "Buff"
	attribute = "ArmorClass"
	polarity = "+"
	value = "1d4 + 2" 
	duration = "Turn"
