name = "Plain Shortsword"

rarity = 500

description = [
	"A simple steel shortsword",
	"A shortsword with a comfortable leather-wrapped grip"
]

[equip]
label = "Wield"
slot = "OnHand"

[[action]]
type = "Attack"
label = "Attack"
damage = "d12"
accuracy = "d20"
damage_type = [ "Slicing", "Body" ]
report = "attack the %{target} for %{damage} damage"

[[action]]
type = "Buff"
label = "Block"
attribute = "ArmorClass"
value = "d12"
duration = 1
report = "attack the %{target} for %{damage} damage"
