name = "Plain Shortsword"
level = 1
rarity = 500

description = [
	"A simple steel shortsword",
	"A shortsword with a comfortable leather-wrapped grip"
]

[equip]
label = "Wield"
slot = "OnHand"

[[action]]
type = "Attack"
label = "Attack"
damage = "1d12 + 5"
accuracy = "1d20 + 5"
damage_type = [ "Slicing", "Body" ]
range = "Melee"
report = "attack the %{target} for %{damage} damage"

[[action]]
type = "Buff"
label = "Block"
attribute = "ArmorClass"
value = "1d4 + 2"
duration = 1
report = "shift into a defenceve stance"
