name = "Ring of Oxen Strength"
rarity = 10

description = [
	"A thick golden ring with carvings of plows and horns",
	"Enamled horns hold a sparkling saphire",
	"The ring glows with a dancing internal light"
]

[equip]
label = "Put on the ring"
slot = ["FingersRight", "FingersLeft"]

[[passive]]
attribute = "Str"
polarity = "+"
value = 2

[[passive]]
attribute = "Con"
polarity = "+"
value = 1

[[passive]]
attribute = "Int"
polarity = "-"
value = 2
